# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 15:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('WID', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=30)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(1, 1), null=True, srid=4326)),
                ('average_yield', models.DecimalField(decimal_places=4, max_digits=7)),
                ('depth', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yield', models.FloatField(blank=True, null=True)),
                ('Date', models.DateField()),
                ('WID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellanalytics.Well')),
            ],
        ),
    ]
